# Generated by Django 3.2.7 on 2021-10-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('origin', models.DateField()),
                ('email', models.EmailField(max_length=30)),
                ('employees_no', models.IntegerField()),
            ],
        ),
    ]
