# Generated by Django 3.2.7 on 2021-10-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branche',
            new_name='Branch',
        ),
    ]
