# Generated by Django 3.2.7 on 2021-10-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211002_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='event_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_coordinator', to='courses.person'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
