# Generated by Django 3.2.7 on 2021-10-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_application_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='narozeni',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='jmeno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='prijmeni',
            new_name='surname',
        ),
    ]
