# Generated by Django 3.2.7 on 2021-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zvire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('vaha', models.IntegerField()),
                ('barva', models.CharField(max_length=40)),
            ],
        ),
    ]
