# Generated by Django 3.2.7 on 2021-12-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvire',
            name='zije',
            field=models.BooleanField(null=True),
        ),
    ]
