# Generated by Django 3.2.7 on 2021-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_auto_20211014_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='clen',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
