# Generated by Django 3.2.7 on 2021-10-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_clen_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clen',
            options={'ordering': ['prezdivka'], 'verbose_name_plural': 'Clenove'},
        ),
    ]
