# Generated by Django 3.2.7 on 2022-01-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clen',
            fields=[
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('prezdivka', models.CharField(max_length=30)),
                ('vek', models.IntegerField(null=True)),
                ('prispevek', models.BooleanField(null=True)),
                ('slug', models.SlugField(blank='True', default='', primary_key=True, serialize=False)),
            ],
        ),
    ]
