# Generated by Django 3.2.7 on 2022-01-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clen',
            options={'ordering': ['prezdivka'], 'verbose_name_plural': 'Clenove'},
        ),
        migrations.AlterField(
            model_name='clen',
            name='slug',
            field=models.SlugField(blank='True', default='', editable=False, primary_key=True, serialize=False),
        ),
    ]
