# Generated by Django 3.2.7 on 2022-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0002_auto_20220102_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='slug',
            field=models.SlugField(blank='True', default='', primary_key=True, serialize=False),
        ),
    ]
