# Generated by Django 3.2.7 on 2022-01-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0003_alter_clen_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulice', models.CharField(max_length=30)),
                ('cislo', models.IntegerField()),
                ('mesto', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.CreateModel(
            name='Bobrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dovednost', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Bobrici',
            },
        ),
        migrations.CreateModel(
            name='Oddil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('vlajka', models.BooleanField()),
                ('sidlo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clenove.adresa')),
            ],
            options={
                'verbose_name_plural': 'Oddily',
            },
        ),
        migrations.AddField(
            model_name='clen',
            name='bobrik',
            field=models.ManyToManyField(to='clenove.Bobrik'),
        ),
        migrations.AddField(
            model_name='clen',
            name='oddil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clenove.oddil'),
        ),
    ]
